name: Build Squirrel

on: [ push, pull_request ]

env:
  DOTNET_VERSION: '6.0.302'

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        shell: pwsh
        run: .\build.ps1
      - name: Test
        run: dotnet test --no-build test\Squirrel.Tests\Squirrel.Tests.csproj -c Release -l "console;verbosity=detailed"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: .\build\Release\*.nupkg
      - name: Publish to GitHub Packages
        shell: pwsh
        run: dotnet nuget push .\build\Release\*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
